# $Id$

TOP = ..

SUBDIR =
SUBDIR+= atf			# ATF based test suites.
SUBDIR+= custom			# Test suites using custom frameworks.
SUBDIR+= tet			# TET based test suites.

SUBDIR+= libtest

.include "${TOP}/mk/elftoolchain.subdir.mk"
