/*
Copyright (C) 2021 The Falco Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/

#ifndef _WIN32
#include <dlfcn.h>
#include <inttypes.h>
#include <string.h>
#include <vector>
#include <sstream>
#endif
#include <json/json.h>

#include "sinsp.h"
#include "sinsp_int.h"
#include "filter.h"
#include "filterchecks.h"
#include "plugin.h"
#include "plugin_evt_processor.h"

#include <third-party/tinydir.h>

using namespace std;

extern sinsp_filter_check_list g_filterlist;

///////////////////////////////////////////////////////////////////////////////
// source_plugin filter check implementation
// This class implements a dynamic filter check that acts as a bridge to the
// plugin simplified field extraction implementations
///////////////////////////////////////////////////////////////////////////////
class sinsp_filter_check_plugin : public sinsp_filter_check
{
public:
	enum check_type
	{
		TYPE_CNT = 0,
	};

	sinsp_filter_check_plugin()
	{
		m_info.m_name = "plugin";
		m_info.m_fields = NULL;
		m_info.m_nfields = 0;
		m_info.m_flags = filter_check_info::FL_NONE;
		m_cnt = 0;
	}

	sinsp_filter_check_plugin(std::shared_ptr<sinsp_plugin> plugin)
	{
		m_plugin = plugin;
		m_info.m_name = plugin->name() + string(" (plugin)");
		m_info.m_fields = plugin->fields();
		m_info.m_nfields = plugin->nfields();
		m_info.m_flags = filter_check_info::FL_NONE;
		m_cnt = 0;
	}

	sinsp_filter_check_plugin(const sinsp_filter_check_plugin &p)
	{
		m_plugin = p.m_plugin;
		m_info = p.m_info;
	}

	virtual ~sinsp_filter_check_plugin()
	{
	}

	int32_t parse_field_name(const char* str, bool alloc_state, bool needed_for_filtering)
	{
		int32_t res = sinsp_filter_check::parse_field_name(str, alloc_state, needed_for_filtering);

		if(res != -1)
		{
			string val(str);
			size_t pos1 = val.find_first_of('[', 0);
			if(pos1 != string::npos)
			{
				size_t argstart = pos1 + 1;
				if(argstart < val.size())
				{
					m_argstr = val.substr(argstart);
					size_t pos2 = m_argstr.find_first_of(']', 0);
					m_argstr = m_argstr.substr(0, pos2);
					m_arg = (char*)m_argstr.c_str();
					return pos1 + pos2 + 2;
				}
			}
		}

		return res;
	}

	sinsp_filter_check* allocate_new()
	{
		return new sinsp_filter_check_plugin(*this);
	}

	uint8_t* extract(sinsp_evt *evt, OUT uint32_t* len, bool sanitize_strings)
	{
		//
		// Reject any event that is not generated by a plugin
		//
		if(evt->get_type() != PPME_PLUGINEVENT_E)
		{
			return NULL;
		}

		//
		// If this is a source plugin, reject events that have
		// not been generated by a plugin with this id specifically.
		//
		// XXX/mstemm this should probably check the version as well.
		//
		sinsp_evt_param *parinfo;
		if(m_plugin->type() == TYPE_SOURCE_PLUGIN)
		{
			sinsp_source_plugin *splugin = static_cast<sinsp_source_plugin *>(m_plugin.get());
			parinfo = evt->get_param(0);
			ASSERT(parinfo->m_len == sizeof(int32_t));
			uint32_t pgid = *(int32_t *)parinfo->m_val;
			if(pgid != splugin->id())
			{
				return NULL;
			}
		}

		//
		// If this is an extractor plugin, only attempt to
		// extract if the source is compatible with the event
		// source.
		//
		if(m_plugin->type() == TYPE_EXTRACTOR_PLUGIN)
		{
			sinsp_extractor_plugin *eplugin = static_cast<sinsp_extractor_plugin *>(m_plugin.get());
			parinfo = evt->get_param(0);
			ASSERT(parinfo->m_len == sizeof(int32_t));
			uint32_t pgid = *(int32_t *)parinfo->m_val;

			std::shared_ptr<sinsp_plugin> plugin = m_inspector->get_plugin_by_id(pgid);

			if(!plugin)
			{
				return NULL;
			}

			sinsp_source_plugin *splugin = static_cast<sinsp_source_plugin *>(plugin.get());

			if(!eplugin->source_compatible(splugin->event_source()))
			{
				return NULL;
			}
		}

		//
		// Get the event payload
		//
		parinfo = evt->get_param(1);
		*len = 0;

		ppm_param_type type = m_info.m_fields[m_field_id].m_type;

		switch(type)
		{
		case PT_CHARBUF:
		{
			if (!m_plugin->extract_str(evt->get_num(), m_info.m_fields[m_field_id].m_name, m_arg, (uint8_t *) parinfo->m_val, parinfo->m_len, m_strstorage))
			{
				return NULL;
			}

			*len = m_strstorage.size();
			return (uint8_t*) m_strstorage.c_str();
		}
		case PT_UINT64:
		{
			uint32_t field_present;

			if (!m_plugin->extract_u64(evt->get_num(), m_info.m_fields[m_field_id].m_name, m_arg, (uint8_t *) parinfo->m_val, parinfo->m_len, field_present, m_u64_res))
			{
				return NULL;
			}

			if(!field_present)
			{
				return NULL;
			}

			return (uint8_t *)&m_u64_res;
		}
		default:
			ASSERT(false);
			throw sinsp_exception("plugin extract error: unsupported field type " + to_string(type));
			break;
		}

		return NULL;
	}

	// XXX/mstemm m_cnt unused so far.
	uint64_t m_cnt;
	string m_argstr;
	char* m_arg = NULL;

	std::string m_strstorage;
	uint64_t m_u64_res;

	std::shared_ptr<sinsp_plugin> m_plugin;
};

///////////////////////////////////////////////////////////////////////////////
// sinsp_plugin implementation
///////////////////////////////////////////////////////////////////////////////
sinsp_plugin::version::version()
	: m_valid(false)
{
}

sinsp_plugin::version::version(const char *version_str)
	: m_valid(false)
{
	if(version_str)
	{
		m_valid = (sscanf(version_str, "%" PRIu32 ".%" PRIu32 ".%" PRIu32,
				  &m_version_major, &m_version_minor, &m_version_patch) == 3);
	}
}

sinsp_plugin::version::~version()
{
}

std::string sinsp_plugin::version::as_string() const
{
	return std::to_string(m_version_major) + "." +
		std::to_string(m_version_minor) + "." +
		std::to_string(m_version_patch);
}

sinsp_plugin::event::event()
	: m_datalen(0), m_ts(0)
{
}

sinsp_plugin::event::event(uint8_t *data, uint32_t datalen, uint64_t ts)
{
	set(data, datalen, ts);
}

sinsp_plugin::event::~event()
{
}

void sinsp_plugin::event::set(uint8_t *data, uint32_t datalen, uint64_t ts)
{
	m_data.reset(data);
	m_datalen = datalen;
	m_ts = ts;
}

const uint8_t *sinsp_plugin::event::data()
{
	return m_data.get();
}

uint32_t sinsp_plugin::event::datalen()
{
	return m_datalen;
}

uint64_t sinsp_plugin::event::ts()
{
	return m_ts;
}

void sinsp_plugin::register_plugin(sinsp* inspector, string filepath, char* config, bool avoid_async)
{
	string errstr;
	std::shared_ptr<sinsp_plugin> plugin = create_plugin(filepath, config, avoid_async, errstr);

	if (!plugin)
	{
		throw sinsp_exception("cannot load plugin " + filepath + ": " + errstr.c_str());
	}

	try
	{
		inspector->add_plugin(plugin);
	}
	catch(sinsp_exception const& e)
	{
		throw sinsp_exception("cannot add plugin " + filepath + " to inspector: " + e.what());
	}

	//
	// Create and register the filter check associated to this plugin
	//
	auto filtercheck = new sinsp_filter_check_plugin(plugin);

	g_filterlist.add_filter_check(filtercheck);
}

std::shared_ptr<sinsp_plugin> sinsp_plugin::create_plugin(string &filepath, char* config, bool avoid_async, std::string &errstr)
{
	std::shared_ptr<sinsp_plugin> ret;

#ifdef _WIN32
	HINSTANCE handle = LoadLibrary(filepath.c_str());
#else
	void* handle = dlopen(filepath.c_str(), RTLD_LAZY);
#endif
	if(handle == NULL)
	{
		errstr = "error loading plugin " + filepath + ": " + strerror(errno);
		return ret;
	}

	// Before doing anything else, check the required api
	// version. If it doesn't match, return an error.

	// The pointer indirection and reference is because c++ doesn't
	// strictly allow casting void * to a function pointer. (See
	// http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_defects.html#195).
	char * (*get_required_api_version)();
	*(void **) (&get_required_api_version) = getsym(handle, "plugin_get_required_api_version", errstr);
	if(get_required_api_version == NULL)
	{
		return ret;
	}

	char *version_str = get_required_api_version();
	version v(version_str);
	if(!v.m_valid)
	{
		errstr = string("Could not parse version string from ") + version_str;
		return ret;
	}

	if(!(v.m_version_major == PLUGIN_API_VERSION_MAJOR && v.m_version_minor <= PLUGIN_API_VERSION_MINOR))
	{
		errstr = string("Unsupported plugin api version ") + std::to_string(v.m_version_major);
		return ret;
	}

	uint32_t (*get_type)();
	*(void **) (&get_type) = getsym(handle, "plugin_get_type", errstr);
	if(get_type == NULL)
	{
		return ret;
	}

	uint32_t plugin_type = get_type();

	sinsp_source_plugin *splugin;
	sinsp_extractor_plugin *eplugin;

	switch(plugin_type)
	{
	case TYPE_SOURCE_PLUGIN:
		splugin = new sinsp_source_plugin();
		if(!splugin->resolve_dylib_symbols(handle, avoid_async, errstr))
		{
			delete splugin;
			return ret;
		}
		ret.reset(splugin);
		break;
	case TYPE_EXTRACTOR_PLUGIN:
		eplugin = new sinsp_extractor_plugin();
		if(!eplugin->resolve_dylib_symbols(handle, avoid_async, errstr))
		{
			delete eplugin;
			return ret;
		}
		ret.reset(eplugin);
		break;
	}

	// Initialize the plugin
	if (!ret->init(config))
	{
		ret = NULL;
	}

	return ret;
}

std::string sinsp_plugin::plugin_infos(sinsp* inspector)
{
	std::ostringstream os;

	for(auto p : inspector->get_plugins())
	{
		os << "Name: " << p->name() << std::endl;
		os << "Description: " << p->description() << std::endl;
		os << "Contact: " << p->contact() << std::endl;
		os << "Version: " << p->plugin_version().as_string() << std::endl;

		if(p->type() == TYPE_SOURCE_PLUGIN)
		{
			sinsp_source_plugin *sp = static_cast<sinsp_source_plugin *>(p.get());
			os << "Type: source plugin" << std::endl;
			os << "ID: " << sp->id() << std::endl;
		}
		else
		{
			os << "Type: extractor plugin" << std::endl;
		}
	}

	return os.str();
}

sinsp_plugin::sinsp_plugin()
	: m_nfields(0)
{
}

sinsp_plugin::~sinsp_plugin()
{
	destroy();
}

bool sinsp_plugin::init(char *config)
{
	if (!m_plugin_info.init)
	{
		return false;
	}

	int32_t rc;

	m_plugin_handle = m_plugin_info.init(config, &rc);
	if(rc != SCAP_SUCCESS)
	{
		// Not calling get_last_error here because there was
		// no valid ss_plugin_t struct returned from init.
		return false;
	}

	return true;
}

void sinsp_plugin::destroy()
{
	if(m_plugin_handle && m_plugin_info.destroy)
	{
		m_plugin_info.destroy(m_plugin_handle);
		m_plugin_handle = NULL;
	}
}

std::string sinsp_plugin::get_last_error()
{
	std::string ret;

	if(m_plugin_handle && m_plugin_info.get_last_error)
	{
		ret = str_from_alloc_charbuf(m_plugin_info.get_last_error(m_plugin_handle));
	}
	else
	{
		ret = "Plugin handle or get_last_error function not defined";
	}

	return ret;
}

const std::string &sinsp_plugin::name()
{
	return m_name;
}

const std::string &sinsp_plugin::description()
{
	return m_description;
}

const std::string &sinsp_plugin::contact()
{
	return m_contact;
}

const sinsp_plugin::version &sinsp_plugin::plugin_version()
{
	return m_plugin_version;
}

const filtercheck_field_info *sinsp_plugin::fields()
{
	return m_fields.get();
}

uint32_t sinsp_plugin::nfields()
{
	return m_nfields;
}

bool sinsp_plugin::extract_str(uint64_t evtnum, const char *field, char *arg, uint8_t *data, uint32_t datalen, std::string &ret)
{
	if(!m_plugin_info.extract_str || !m_plugin_handle)
	{
		return false;
	}

	if(m_async_extractor)
	{
		return m_async_extractor->extract_str(evtnum, field, arg, data, datalen, ret);
	}

	char *str = m_plugin_info.extract_str(m_plugin_handle, evtnum, field, arg, data, datalen);

	if (str == NULL)
	{
		return false;
	}

	ret = str_from_alloc_charbuf(str);

	return true;
}

bool sinsp_plugin::extract_u64(uint64_t evtnum, const char *field, char *arg, uint8_t *data, uint32_t datalen, uint32_t &field_present, uint64_t &ret)
{
	if(!m_plugin_info.extract_str || !m_plugin_handle)
	{
		return false;
	}

	if(m_async_extractor)
	{
		return m_async_extractor->extract_u64(evtnum, field, arg, data, datalen, field_present, ret);
	}

	uint32_t fp;

	ret = m_plugin_info.extract_u64(m_plugin_handle, evtnum, field, arg, data, datalen, &fp);

	field_present = fp;

	return true;
}

void* sinsp_plugin::getsym(void* handle, const char* name, std::string &errstr)
{
	void *ret;

#ifdef _WIN32
	ret = GetProcAddress((HINSTANCE)handle, name);
#else
	ret = dlsym(handle, name);
#endif

	if(ret == NULL)
	{
		errstr = string("Dynamic library symbol ") + name + " not present";
	}

	return ret;
}

// Used below--set a std::string from the provided allocated charbuf and free() the charbuf.
std::string sinsp_plugin::str_from_alloc_charbuf(char *charbuf)
{
	std::string str;

	if(charbuf != NULL)
	{
		str = charbuf;
		free(charbuf);
	}

	return str;
}

bool sinsp_plugin::resolve_dylib_symbols(void *handle, bool avoid_async, std::string &errstr)
{
	// Some functions are required and return false if not found.
	if((*(void **) (&(m_plugin_info.get_last_error)) = getsym(handle, "plugin_get_last_error", errstr)) == NULL ||
	   (*(void **) (&(m_plugin_info.get_name)) = getsym(handle, "plugin_get_name", errstr)) == NULL ||
	   (*(void **) (&(m_plugin_info.get_description)) = getsym(handle, "plugin_get_description", errstr)) == NULL ||
	   (*(void **) (&(m_plugin_info.get_contact)) = getsym(handle, "plugin_get_contact", errstr)) == NULL ||
	   (*(void **) (&(m_plugin_info.get_version)) = getsym(handle, "plugin_get_version", errstr)) == NULL)
	{
		return false;
	}

	// Others are not and the values will be checked when needed.
	(*(void **) (&m_plugin_info.init)) = getsym(handle, "plugin_init", errstr);
	(*(void **) (&m_plugin_info.destroy)) = getsym(handle, "plugin_destroy", errstr);
	(*(void **) (&m_plugin_info.get_fields)) = getsym(handle, "plugin_get_fields", errstr);
	(*(void **) (&m_plugin_info.extract_str)) = getsym(handle, "plugin_extract_str", errstr);
	(*(void **) (&m_plugin_info.extract_u64)) = getsym(handle, "plugin_extract_u64", errstr);
	(*(void **) (&m_plugin_info.register_async_extractor)) = getsym(handle, "plugin_register_async_extractor", errstr);

	m_name = str_from_alloc_charbuf(m_plugin_info.get_name());
	m_description = str_from_alloc_charbuf(m_plugin_info.get_description());
	m_contact = str_from_alloc_charbuf(m_plugin_info.get_contact());
	char *version_str = m_plugin_info.get_version();
	m_plugin_version = sinsp_plugin::version(version_str);
	if(!m_plugin_version.m_valid)
	{
		errstr = string("Could not parse version string from ") + version_str;
		return false;
	}

	//
	// If filter fields are exported by the plugin, get the json from get_fields(),
	// parse it, create our list of fields, and create a filtercheck from the fields.
	//
	if(m_plugin_info.get_fields)
	{
		char* sfields = m_plugin_info.get_fields();
		if(sfields == NULL)
		{
			throw sinsp_exception(string("error in plugin ") + m_name + ": get_fields returned a null string");
		}
		string json(sfields);
		SINSP_DEBUG("Parsing Fields JSON=%s", json.c_str());
		Json::Value root;
		if(Json::Reader().parse(json, root) == false || root.type() != Json::arrayValue)
		{
			throw sinsp_exception(string("error in plugin ") + m_name + ": get_fields returned an invalid JSON");
		}

		filtercheck_field_info *fields = new filtercheck_field_info[root.size()];
		if(fields == NULL)
		{
			throw sinsp_exception(string("error in plugin ") + m_name + ": could not allocate memory");
		}

		// Take ownership of the pointer right away so it can't be leaked.
		m_fields.reset(fields);
		m_nfields = root.size();

		for(Json::Value::ArrayIndex j = 0; j < root.size(); j++)
		{
			filtercheck_field_info &tf = m_fields.get()[j];
			tf.m_flags = EPF_NONE;

			const Json::Value &jvtype = root[j]["type"];
			string ftype = jvtype.asString();
			if(ftype == "")
			{
				throw sinsp_exception(string("error in plugin ") + m_name + ": field JSON entry has no type");
			}
			const Json::Value &jvname = root[j]["name"];
			string fname = jvname.asString();
			if(fname == "")
			{
				throw sinsp_exception(string("error in plugin ") + m_name + ": field JSON entry has no name");
			}
			const Json::Value &jvdesc = root[j]["desc"];
			string fdesc = jvdesc.asString();
			if(fdesc == "")
			{
				throw sinsp_exception(string("error in plugin ") + m_name + ": field JSON entry has no desc");
			}

			strncpy(tf.m_name, fname.c_str(), sizeof(tf.m_name));
			strncpy(tf.m_description, fdesc.c_str(), sizeof(tf.m_description));
			tf.m_print_format = PF_DEC;
			if(ftype == "string")
			{
				tf.m_type = PT_CHARBUF;
			}
			else if(ftype == "uint64")
			{
				tf.m_type = PT_UINT64;
			}
			// XXX/mstemm are these actually supported?
			else if(ftype == "int64")
			{
				tf.m_type = PT_INT64;
			}
			else if(ftype == "float")
			{
				tf.m_type = PT_DOUBLE;
			}
			else
			{
				throw sinsp_exception(string("error in plugin ") + m_name + ": invalid field type " + ftype);
			}
		}

		if(m_plugin_info.register_async_extractor && !avoid_async)
		{
			m_async_extractor.reset(new sinsp_async_extractor());

			if(m_plugin_info.register_async_extractor(m_plugin_handle, m_async_extractor->extractor_info()) != SCAP_SUCCESS)
			{
				throw sinsp_exception(string("error in plugin ") + m_name + ": " + get_last_error());
			}
		}
	}

	return true;
}

void sinsp_plugin::disable_async_extract()
{
	m_async_extractor.reset();
}

sinsp_source_plugin::sinsp_source_plugin()
	: m_instance_handle(NULL)
{
}

sinsp_source_plugin::~sinsp_source_plugin()
{
	close();
}

uint32_t sinsp_source_plugin::id()
{
	return m_id;
}

const std::string &sinsp_source_plugin::event_source()
{
	return m_event_source;
}

source_plugin_info *sinsp_source_plugin::plugin_info()
{
	return &m_source_plugin_info;
}

bool sinsp_source_plugin::open(char *params, int32_t &rc)
{
	int32_t orc;

	if(!m_plugin_handle)
	{
		return false;
	}

	m_instance_handle = m_source_plugin_info.open(m_plugin_handle, params, &orc);

	rc = orc;

	return (m_instance_handle != NULL);
}

void sinsp_source_plugin::close()
{
	if(!m_plugin_handle || !m_instance_handle)
	{
		return;
	}

	m_source_plugin_info.close(m_plugin_handle, m_instance_handle);
}

int32_t sinsp_source_plugin::next(sinsp_plugin::event &evt, std::string &errbuf)
{
	uint8_t *data;
	uint32_t datalen;
	uint64_t ts;

	if(!m_instance_handle)
	{
		errbuf = "Plugin not open()ed";
		return SCAP_FAILURE;
	}

	int32_t rc = m_source_plugin_info.next(m_plugin_handle, m_instance_handle, &data, &datalen, &ts);

	if(rc == SCAP_FAILURE)
	{
		errbuf = get_last_error();
		return rc;
	}

	if(rc == SCAP_SUCCESS)
	{
		evt.set(data, datalen, ts);
	}

	return rc;
}

int32_t sinsp_source_plugin::next_batch(std::vector<sinsp_plugin::event> &events, std::string &errbuf)
{
	uint32_t nevts;
	uint8_t **datav;
	uint32_t *datalenv;
	uint64_t *tsv;

	if(!m_instance_handle)
	{
		errbuf = "Plugin not open()ed";
		return SCAP_FAILURE;
	}

	int32_t rc = m_source_plugin_info.next_batch(m_plugin_handle, m_instance_handle, &nevts, &datav, &datalenv, &tsv);

	if(rc == SCAP_FAILURE)
	{
		errbuf = get_last_error();
		return rc;
	}

	if(rc == SCAP_SUCCESS)
	{
		events.clear();

		for(uint32_t i = 0; i < nevts; i++)
		{
			sinsp_plugin::event evt(datav[i], datalenv[i], tsv[i]);
			events.push_back(evt);
		}
	}

	return rc;
}

std::string sinsp_source_plugin::get_progress(uint32_t &progress_pct)
{
	std::string ret;
	progress_pct = 0;

	if(!m_source_plugin_info.get_progress || !m_instance_handle)
	{
		return ret;
	}

	uint32_t ppct;
	ret = str_from_alloc_charbuf(m_source_plugin_info.get_progress(m_plugin_handle, m_instance_handle, &ppct));

	progress_pct = ppct;

	return ret;
}

std::string sinsp_source_plugin::event_to_string(const uint8_t *data, uint32_t datalen)
{
	std::string ret = "<NA>";

	if (!m_source_plugin_info.event_to_string)
	{
		return ret;
	}

	ret = str_from_alloc_charbuf(m_source_plugin_info.event_to_string(m_plugin_handle, data, datalen));

	return ret;
}

bool sinsp_source_plugin::resolve_dylib_symbols(void *handle, bool avoid_async, std::string &errstr)
{
	if (!sinsp_plugin::resolve_dylib_symbols(handle, avoid_async, errstr))
	{
		return false;
	}

	// We resolve every symbol, even those that are not actually
	// used by this derived class, just to ensure that
	// m_source_plugin_info is complete. (The struct can be passed
	// down to libscap when reading/writing capture files).
	//
	// Some functions are required and return false if not found.
	if((*(void **) (&(m_source_plugin_info.get_required_api_version)) = getsym(handle, "plugin_get_required_api_version", errstr)) == NULL ||
	   (*(void **) (&(m_source_plugin_info.init)) = getsym(handle, "plugin_init", errstr)) == NULL ||
	   (*(void **) (&(m_source_plugin_info.destroy)) = getsym(handle, "plugin_destroy", errstr)) == NULL ||
	   (*(void **) (&(m_source_plugin_info.get_last_error)) = getsym(handle, "plugin_get_last_error", errstr)) == NULL ||
	   (*(void **) (&(m_source_plugin_info.get_type)) = getsym(handle, "plugin_get_type", errstr)) == NULL ||
	   (*(void **) (&(m_source_plugin_info.get_id)) = getsym(handle, "plugin_get_id", errstr)) == NULL ||
	   (*(void **) (&(m_source_plugin_info.get_name)) = getsym(handle, "plugin_get_name", errstr)) == NULL ||
	   (*(void **) (&(m_source_plugin_info.get_description)) = getsym(handle, "plugin_get_description", errstr)) == NULL ||
	   (*(void **) (&(m_source_plugin_info.get_contact)) = getsym(handle, "plugin_get_contact", errstr)) == NULL ||
	   (*(void **) (&(m_source_plugin_info.get_version)) = getsym(handle, "plugin_get_version", errstr)) == NULL ||
	   (*(void **) (&(m_source_plugin_info.get_event_source)) = getsym(handle, "plugin_get_event_source", errstr)) == NULL ||
	   (*(void **) (&(m_source_plugin_info.open)) = getsym(handle, "plugin_open", errstr)) == NULL ||
	   (*(void **) (&(m_source_plugin_info.close)) = getsym(handle, "plugin_close", errstr)) == NULL ||
	   (*(void **) (&(m_source_plugin_info.next)) = getsym(handle, "plugin_next", errstr)) == NULL ||
	   (*(void **) (&(m_source_plugin_info.event_to_string)) = getsym(handle, "plugin_event_to_string", errstr)) == NULL)
	{
		return false;
	}

	// Others are not.
	(*(void **) (&m_source_plugin_info.get_fields)) = getsym(handle, "plugin_get_fields", errstr);
	(*(void **) (&m_source_plugin_info.get_progress)) = getsym(handle, "plugin_get_progress", errstr);
	(*(void **) (&m_source_plugin_info.event_to_string)) = getsym(handle, "plugin_event_to_string", errstr);
	(*(void **) (&m_source_plugin_info.extract_str)) = getsym(handle, "plugin_extract_str", errstr);
	(*(void **) (&m_source_plugin_info.extract_u64)) = getsym(handle, "plugin_extract_u64", errstr);
	(*(void **) (&m_source_plugin_info.next_batch)) = getsym(handle, "plugin_next_batch", errstr);
	(*(void **) (&m_source_plugin_info.register_async_extractor)) = getsym(handle, "plugin_register_async_extractor", errstr);

	m_id = m_source_plugin_info.get_id();
	m_event_source = str_from_alloc_charbuf(m_source_plugin_info.get_event_source());

	return true;
}

sinsp_extractor_plugin::sinsp_extractor_plugin()
{
}

sinsp_extractor_plugin::~sinsp_extractor_plugin()
{
}

const std::set<std::string> &sinsp_extractor_plugin::extract_event_sources()
{
	return m_extract_event_sources;
}

bool sinsp_extractor_plugin::source_compatible(const std::string &source)
{
	return(m_extract_event_sources.find(source) != m_extract_event_sources.end());
}

bool sinsp_extractor_plugin::resolve_dylib_symbols(void *handle, bool avoid_async, std::string &errstr)
{
	if (!sinsp_plugin::resolve_dylib_symbols(handle, avoid_async, errstr))
	{
		return false;
	}

	// We resolve every symbol, even those that are not actually
	// used by this derived class, just to ensure that
	// m_extractor_plugin_info is complete. (The struct can be passed
	// down to libscap when reading/writing capture files).
	//
	// Some functions are required and return false if not found.
	if((*(void **) (&(m_extractor_plugin_info.get_required_api_version)) = getsym(handle, "plugin_get_required_api_version", errstr)) == NULL ||
	   (*(void **) (&(m_extractor_plugin_info.init)) = getsym(handle, "plugin_init", errstr)) == NULL ||
	   (*(void **) (&(m_extractor_plugin_info.destroy)) = getsym(handle, "plugin_destroy", errstr)) == NULL ||
	   (*(void **) (&(m_extractor_plugin_info.get_last_error)) = getsym(handle, "plugin_get_last_error", errstr)) == NULL ||
	   (*(void **) (&(m_extractor_plugin_info.get_type)) = getsym(handle, "plugin_get_type", errstr)) == NULL ||
	   (*(void **) (&(m_extractor_plugin_info.get_name)) = getsym(handle, "plugin_get_name", errstr)) == NULL ||
	   (*(void **) (&(m_extractor_plugin_info.get_description)) = getsym(handle, "plugin_get_description", errstr)) == NULL ||
	   (*(void **) (&(m_extractor_plugin_info.get_contact)) = getsym(handle, "plugin_get_contact", errstr)) == NULL ||
	   (*(void **) (&(m_extractor_plugin_info.get_version)) = getsym(handle, "plugin_get_version", errstr)) == NULL ||
	   (*(void **) (&(m_extractor_plugin_info.get_fields)) = getsym(handle, "plugin_get_fields", errstr)) == NULL ||
	   (*(void **) (&(m_extractor_plugin_info.extract_str)) = getsym(handle, "plugin_extract_str", errstr)) == NULL ||
	   (*(void **) (&(m_extractor_plugin_info.extract_u64)) = getsym(handle, "plugin_extract_u64", errstr)) == NULL)
	{
		return false;
	}

	// Others are not.
	(*(void **) (&m_extractor_plugin_info.get_extract_event_sources)) = getsym(handle, "plugin_get_extract_event_sources", errstr);

	if (m_extractor_plugin_info.get_extract_event_sources != NULL)
	{
		std::string esources = str_from_alloc_charbuf(m_extractor_plugin_info.get_extract_event_sources());

		if (esources.length() == 0)
		{
			throw sinsp_exception(string("error in plugin ") + name() + ": get_extract_event_sources returned an empty string");
		}

		Json::Value root;
		if(Json::Reader().parse(esources, root) == false || root.type() != Json::arrayValue)
		{
			throw sinsp_exception(string("error in plugin ") + name() + ": get_extract_event_sources did not return a json array");
		}

		for(Json::Value::ArrayIndex j = 0; j < root.size(); j++)
		{
			if(! root[j].isConvertibleTo(Json::stringValue))
			{
				throw sinsp_exception(string("error in plugin ") + name() + ": get_extract_event_sources did not return a json array");
			}

			m_extract_event_sources.insert(root[j].asString());
		}
	}

	return true;
}


