coverage:
  status:
    project:
      default: off
      libsinsp:
        flags:
          - libsinsp

flags:
  libsinsp:
    paths:
      - userspace/libsinsp/

parsers:
  cobertura:
    partials_as_hits: true
