site_name: Falco Kernel Testing
site_url: https://github.com/alacuku/e2e-falco-tests/
nav:
    - Home: index.md
    - Matrixes:
      - amd64: matrix_X64.md
      - arm64: matrix_ARM64.md
    - Syscalls Report: report.md

theme: material
