# $Id: Makefile 4029 2024-01-15 16:16:49Z jkoshy $

TOP=	../../../../..

TS_SRCS=		ehdr.m4
TS_DATA=		ehdr.msb64 ehdr.lsb64 ehdr.msb32 ehdr.lsb32 \
			ehdr-malformed-1.lsb64 ehdr-malformed-1.msb64 \
			newehdr.lsb64 newehdr.msb64

.include "${TOP}/mk/elftoolchain.tet.mk"
