# $Id: Makefile 4029 2024-01-15 16:16:49Z jkoshy $

TOP=	../../../../..

TS_SRCS=		phdr.m4
TS_DATA=		ehdr.lsb64 ehdr.msb64 \
			phdr.lsb32 phdr.msb32 phdr.msb64 phdr.lsb64

.include "${TOP}/mk/elftoolchain.tet.mk"
