// SPDX-License-Identifier: Apache-2.0
/*
Copyright (C) 2025 The Falco Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/

#include "events_prog_table.h"
#include "state.h"

/*
 * For every exit event here we have the name of the corresponding bpf program.
 * We can have multiple names in case we need to check the right program
 * that needs to be loaded, eg: because of different bpf features.
 */
event_prog_t exit_event_progs_table[PPM_EVENT_MAX][MAX_FEATURE_CHECKS] = {
        [PPME_GENERIC_X] = {{.name = "generic_x"}},
        [PPME_SYSCALL_GETCWD_X] = {{.name = "getcwd_x"}},
        [PPME_SYSCALL_GETDENTS_X] = {{.name = "getdents_x"}},
        [PPME_SYSCALL_GETDENTS64_X] = {{.name = "getdents64_x"}},
        [PPME_SYSCALL_EPOLLWAIT_X] = {{.name = "epoll_wait_x"}},
        [PPME_SOCKET_GETPEERNAME_X] = {{.name = "getpeername_x"}},
        [PPME_SOCKET_GETSOCKNAME_X] = {{.name = "getsockname_x"}},
        [PPME_SYSCALL_MKDIR_2_X] = {{.name = "mkdir_x"}},
        [PPME_SYSCALL_MMAP_X] = {{.name = "mmap_x"}},
        [PPME_SYSCALL_MUNMAP_X] = {{.name = "munmap_x"}},
        [PPME_SYSCALL_OPEN_X] = {{.name = "open_x"}},
        [PPME_SYSCALL_OPENAT_2_X] = {{.name = "openat_x"}},
        [PPME_SYSCALL_OPENAT2_X] = {{.name = "openat2_x"}},
        [PPME_SYSCALL_OPEN_BY_HANDLE_AT_X] = {{.name = "open_by_handle_at_x"}},
        [PPME_SYSCALL_CLOSE_X] = {{.name = "close_x"}},
        [PPME_SYSCALL_COPY_FILE_RANGE_X] = {{.name = "copy_file_range_x"}},
        [PPME_SYSCALL_CREAT_X] = {{.name = "creat_x"}},
        [PPME_SYSCALL_DUP_1_X] = {{.name = "dup_x"}},
        [PPME_SYSCALL_DUP2_X] = {{.name = "dup2_x"}},
        [PPME_SYSCALL_DUP3_X] = {{.name = "dup3_x"}},
        [PPME_SYSCALL_CHDIR_X] = {{.name = "chdir_x"}},
        [PPME_SYSCALL_CHMOD_X] = {{.name = "chmod_x"}},
        [PPME_SYSCALL_CHROOT_X] = {{.name = "chroot_x"}},
        [PPME_SYSCALL_FCHDIR_X] = {{.name = "fchdir_x"}},
        [PPME_SYSCALL_FCHMOD_X] = {{.name = "fchmod_x"}},
        [PPME_SYSCALL_FCHMODAT_X] = {{.name = "fchmodat_x"}},
        [PPME_SYSCALL_MKDIRAT_X] = {{.name = "mkdirat_x"}},
        [PPME_SYSCALL_RMDIR_2_X] = {{.name = "rmdir_x"}},
        [PPME_SYSCALL_EVENTFD_X] = {{.name = "eventfd_x"}},
        [PPME_SYSCALL_INOTIFY_INIT_X] = {{.name = "inotify_init_x"}},
        [PPME_SYSCALL_TIMERFD_CREATE_X] = {{.name = "timerfd_create_x"}},
        [PPME_SYSCALL_USERFAULTFD_X] = {{.name = "userfaultfd_x"}},
        [PPME_SYSCALL_SIGNALFD_X] = {{.name = "signalfd_x"}},
        [PPME_SYSCALL_KILL_X] = {{.name = "kill_x"}},
        [PPME_SYSCALL_TGKILL_X] = {{.name = "tgkill_x"}},
        [PPME_SYSCALL_TKILL_X] = {{.name = "tkill_x"}},
        [PPME_SYSCALL_SECCOMP_X] = {{.name = "seccomp_x"}},
        [PPME_SYSCALL_PTRACE_X] = {{.name = "ptrace_x"}},
        [PPME_SYSCALL_CAPSET_X] = {{.name = "capset_x"}},
        [PPME_SOCKET_SOCKET_X] = {{.name = "socket_x"}},
        [PPME_SOCKET_CONNECT_X] = {{.name = "connect_x"}},
        [PPME_SOCKET_SOCKETPAIR_X] = {{.name = "socketpair_x"}},
        [PPME_SOCKET_ACCEPT_5_X] = {{.name = "accept_x"}},
        [PPME_SOCKET_BIND_X] = {{.name = "bind_x"}},
        [PPME_SOCKET_LISTEN_X] = {{.name = "listen_x"}},
        [PPME_SYSCALL_EXECVE_19_X] = {{.name = "execve_x"}},
        [PPME_SYSCALL_EXECVEAT_X] = {{.name = "execveat_x"}},
        [PPME_SYSCALL_CLONE_20_X] = {{.name = "clone_x"}},
        [PPME_SYSCALL_CLONE3_X] = {{.name = "clone3_x"}},
        [PPME_SYSCALL_FORK_20_X] = {{.name = "fork_x"}},
        [PPME_SYSCALL_VFORK_20_X] = {{.name = "vfork_x"}},
        [PPME_SYSCALL_RENAME_X] = {{.name = "rename_x"}},
        [PPME_SYSCALL_RENAMEAT_X] = {{.name = "renameat_x"}},
        [PPME_SYSCALL_RENAMEAT2_X] = {{.name = "renameat2_x"}},
        [PPME_SYSCALL_PIPE_X] = {{.name = "pipe_x"}},
        [PPME_SYSCALL_READV_X] = {{.name = "readv_x"}},
        [PPME_SYSCALL_PREADV_X] = {{.name = "preadv_x"}},
        [PPME_SYSCALL_PREAD_X] = {{.name = "pread64_x"}},
        [PPME_SYSCALL_BPF_2_X] = {{.name = "bpf_x"}},
        [PPME_SYSCALL_FLOCK_X] = {{.name = "flock_x"}},
        [PPME_SYSCALL_IOCTL_3_X] = {{.name = "ioctl_x"}},
        [PPME_SYSCALL_QUOTACTL_X] = {{.name = "quotactl_x"}},
        [PPME_SYSCALL_UNSHARE_X] = {{.name = "unshare_x"}},
        [PPME_SYSCALL_MOUNT_X] = {{.name = "mount_x"}},
        [PPME_SYSCALL_UMOUNT2_X] = {{.name = "umount2_x"}},
        [PPME_SYSCALL_LINK_2_X] = {{.name = "link_x"}},
        [PPME_SYSCALL_LINKAT_2_X] = {{.name = "linkat_x"}},
        [PPME_SYSCALL_SYMLINK_X] = {{.name = "symlink_x"}},
        [PPME_SYSCALL_SYMLINKAT_X] = {{.name = "symlinkat_x"}},
        [PPME_SYSCALL_UNLINK_2_X] = {{.name = "unlink_x"}},
        [PPME_SYSCALL_UNLINKAT_2_X] = {{.name = "unlinkat_x"}},
        [PPME_SYSCALL_SETGID_X] = {{.name = "setgid_x"}},
        [PPME_SYSCALL_SETUID_X] = {{.name = "setuid_x"}},
        [PPME_SYSCALL_SETNS_X] = {{.name = "setns_x"}},
        [PPME_SYSCALL_SETPGID_X] = {{.name = "setpgid_x"}},
        [PPME_SYSCALL_SETRESGID_X] = {{.name = "setresgid_x"}},
        [PPME_SYSCALL_SETRESUID_X] = {{.name = "setresuid_x"}},
        [PPME_SYSCALL_SETSID_X] = {{.name = "setsid_x"}},
        [PPME_SYSCALL_SETRLIMIT_X] = {{.name = "setrlimit_x"}},
        [PPME_SYSCALL_PRLIMIT_X] = {{.name = "prlimit64_x"}},
        [PPME_SOCKET_SETSOCKOPT_X] = {{.name = "setsockopt_x"}},
        [PPME_SOCKET_SENDMSG_X] = {{.name = "sendmsg_x"}},
        [PPME_SOCKET_SENDTO_X] = {{.name = "sendto_x"}},
        [PPME_SOCKET_RECVMSG_X] = {{.name = "recvmsg_x"}},
        [PPME_SOCKET_RECVFROM_X] = {{.name = "recvfrom_x"}},
        [PPME_SYSCALL_FCNTL_X] = {{.name = "fcntl_x"}},
        [PPME_SOCKET_SHUTDOWN_X] = {{.name = "shutdown_x"}},
        [PPME_SYSCALL_FSCONFIG_X] = {{.name = "fsconfig_x"}},
        [PPME_SYSCALL_EPOLL_CREATE_X] = {{.name = "epoll_create_x"}},
        [PPME_SYSCALL_EPOLL_CREATE1_X] = {{.name = "epoll_create1_x"}},
        [PPME_SYSCALL_ACCESS_X] = {{.name = "access_x"}},
        [PPME_SOCKET_GETSOCKOPT_X] = {{.name = "getsockopt_x"}},
        [PPME_SYSCALL_MPROTECT_X] = {{.name = "mprotect_x"}},
        [PPME_SYSCALL_GETUID_X] = {{.name = "getuid_x"}},
        [PPME_SYSCALL_GETGID_X] = {{.name = "getgid_x"}},
        [PPME_SYSCALL_GETEUID_X] = {{.name = "geteuid_x"}},
        [PPME_SYSCALL_GETEGID_X] = {{.name = "getegid_x"}},
        [PPME_SYSCALL_MLOCK_X] = {{.name = "mlock_x"}},
        [PPME_SYSCALL_MLOCK2_X] = {{.name = "mlock2_x"}},
        [PPME_SYSCALL_MUNLOCK_X] = {{.name = "munlock_x"}},
        [PPME_SYSCALL_MLOCKALL_X] = {{.name = "mlockall_x"}},
        [PPME_SYSCALL_MUNLOCKALL_X] = {{.name = "munlockall_x"}},
        [PPME_SYSCALL_READ_X] = {{.name = "read_x"}},
        [PPME_SYSCALL_IO_URING_ENTER_X] = {{.name = "io_uring_enter_x"}},
        [PPME_SYSCALL_IO_URING_REGISTER_X] = {{.name = "io_uring_register_x"}},
        [PPME_SYSCALL_IO_URING_SETUP_X] = {{.name = "io_uring_setup_x"}},
        [PPME_SYSCALL_POLL_X] = {{.name = "poll_x"}},
        [PPME_SYSCALL_PPOLL_X] = {{.name = "ppoll_x"}},
        [PPME_SYSCALL_MMAP2_X] = {{.name = "mmap2_x"}},
        [PPME_SYSCALL_SEMGET_X] = {{.name = "semget_x"}},
        [PPME_SYSCALL_SEMCTL_X] = {{.name = "semctl_x"}},
        [PPME_SYSCALL_SELECT_X] = {{.name = "select_x"}},
        [PPME_SYSCALL_SPLICE_X] = {{.name = "splice_x"}},
        [PPME_SOCKET_RECVMMSG_X] = {{.name = "recvmmsg_x",
                                     .feat = BPF_FUNC_loop,
                                     .needs_bpf_atomics = true},
                                    {.name = "recvmmsg_old_x"}},
        [PPME_SOCKET_SENDMMSG_X] = {{.name = "sendmmsg_x",
                                     .feat = BPF_FUNC_loop,
                                     .needs_bpf_atomics = true},
                                    {.name = "sendmmsg_old_x"}},
        [PPME_SYSCALL_SEMOP_X] = {{.name = "semop_x"}},
        [PPME_SYSCALL_GETRESUID_X] = {{.name = "getresuid_x"}},
        [PPME_SYSCALL_SENDFILE_X] = {{.name = "sendfile_x"}},
        [PPME_SYSCALL_FUTEX_X] = {{.name = "futex_x"}},
        [PPME_SYSCALL_STAT_X] = {{.name = "stat_x"}},
        [PPME_SYSCALL_LSTAT_X] = {{.name = "lstat_x"}},
        [PPME_SYSCALL_FSTAT_X] = {{.name = "fstat_x"}},
        [PPME_SYSCALL_LSEEK_X] = {{.name = "lseek_x"}},
        [PPME_SYSCALL_LLSEEK_X] = {{.name = "llseek_x"}},
        [PPME_SYSCALL_WRITE_X] = {{.name = "write_x"}},
        [PPME_SYSCALL_WRITEV_X] = {{.name = "writev_x"}},
        [PPME_SYSCALL_PWRITEV_X] = {{.name = "pwritev_x"}},
        [PPME_SYSCALL_PWRITE_X] = {{.name = "pwrite64_x"}},
        [PPME_SYSCALL_GETRESGID_X] = {{.name = "getresgid_x"}},
        [PPME_SYSCALL_CHOWN_X] = {{.name = "chown_x"}},
        [PPME_SYSCALL_LCHOWN_X] = {{.name = "lchown_x"}},
        [PPME_SYSCALL_FCHOWN_X] = {{.name = "fchown_x"}},
        [PPME_SYSCALL_FCHOWNAT_X] = {{.name = "fchownat_x"}},
        [PPME_SYSCALL_BRK_4_X] = {{.name = "brk_x"}},
        [PPME_SYSCALL_GETRLIMIT_X] = {{.name = "getrlimit_x"}},
        [PPME_SOCKET_SEND_X] = {{.name = "send_x"}},
        [PPME_SOCKET_RECV_X] = {{.name = "recv_x"}},
        [PPME_SYSCALL_NANOSLEEP_X] = {{.name = "nanosleep_x"}},
        [PPME_SYSCALL_UMOUNT_1_X] = {{.name = "umount_x"}},
        [PPME_SOCKET_ACCEPT4_6_X] = {{.name = "accept4_x"}},
        [PPME_SYSCALL_PIPE2_X] = {{.name = "pipe2_x"}},
        [PPME_SYSCALL_INOTIFY_INIT1_X] = {{.name = "inotify_init1_x"}},
        [PPME_SYSCALL_EVENTFD2_X] = {{.name = "eventfd2_x"}},
        [PPME_SYSCALL_SIGNALFD4_X] = {{.name = "signalfd4_x"}},
        [PPME_SYSCALL_PRCTL_X] = {{.name = "prctl_x"}},
        [PPME_SYSCALL_MEMFD_CREATE_X] = {{.name = "memfd_create_x"}},
        [PPME_SYSCALL_PIDFD_GETFD_X] = {{.name = "pidfd_getfd_x"}},
        [PPME_SYSCALL_PIDFD_OPEN_X] = {{.name = "pidfd_open_x"}},
        [PPME_SYSCALL_INIT_MODULE_X] = {{.name = "init_module_x"}},
        [PPME_SYSCALL_FINIT_MODULE_X] = {{.name = "finit_module_x"}},
        [PPME_SYSCALL_MKNOD_X] = {{.name = "mknod_x"}},
        [PPME_SYSCALL_MKNODAT_X] = {{.name = "mknodat_x"}},
        [PPME_SYSCALL_NEWFSTATAT_X] = {{.name = "newfstatat_x"}},
        [PPME_SYSCALL_PROCESS_VM_READV_X] = {{.name = "process_vm_readv_x"}},
        [PPME_SYSCALL_PROCESS_VM_WRITEV_X] = {{.name = "process_vm_writev_x"}},
        [PPME_SYSCALL_DELETE_MODULE_X] = {{.name = "delete_module_x"}},
        [PPME_SYSCALL_SETREUID_X] = {{.name = "setreuid_x"}},
        [PPME_SYSCALL_SETREGID_X] = {{.name = "setregid_x"}},
        [PPME_SYSCALL_CLOSE_RANGE_X] = {{.name = "close_range_x"}},
        [PPME_SYSCALL_KEYCTL_X] = {{.name = "keyctl_x"}},
};

ttm_progs_t ttm_progs_table[TTM_MAX] = {
        [TTM_CONNECT] = {{"connect_e"},
                         {{"ia32_compat_connect_e", "__ia32_compat_sys_connect"},
                          {"ia32_connect_e", "__ia32_sys_connect"}}},
        [TTM_CREAT] = {{"creat_e"},
                       {{"ia32_compat_creat_e", "__ia32_compat_sys_creat"},
                        {"ia32_creat_e", "__ia32_sys_creat"}}},
        [TTM_OPEN] = {{"open_e"},
                      {{"ia32_compat_open_e", "__ia32_compat_sys_open"},
                       {"ia32_open_e", "__ia32_sys_open"}}},
        [TTM_OPENAT] = {{"openat_e"},
                        {{"ia32_compat_openat_e", "__ia32_compat_sys_openat"},
                         {"ia32_openat_e", "__ia32_sys_openat"}}},
        [TTM_OPENAT2] = {{"openat2_e"},
                         {{"ia32_compat_openat2_e", "__ia32_compat_sys_openat2"},
                          {"ia32_openat2_e", "__ia32_sys_openat2"}}},
};

#ifdef BPF_ITERATOR_SUPPORT
iter_prog_t iter_progs_table[ITER_PROG_MAX] = {
        [ITER_PROG_DUMP_TASK] = {"dump_task", &g_state.is_tasks_dumping_supported},
        [ITER_PROG_DUMP_TASK_FILE] = {"dump_task_file", &g_state.is_task_files_dumping_supported},
};
#endif /* BPF_ITERATOR_SUPPORT */
