// SPDX-License-Identifier: Apache-2.0
/*
Copyright (C) 2025 The Falco Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

*/

#include "events_prog_table.h"
/*
 * For every event here we have the name of the corresponding bpf program.
 * We can have multiple names in case we need to check the right program
 * that needs to be loaded, eg: because of different bpf features.
 */
event_prog_t event_prog_table[PPM_EVENT_MAX][MAX_FEATURE_CHECKS] = {
        [PPME_GENERIC_E] = {{false, "generic_e", 0}},
        [PPME_GENERIC_X] = {{false, "generic_x", 0}},
        [PPME_SYSCALL_GETCWD_E] = {{false, "getcwd_e", 0}},
        [PPME_SYSCALL_GETCWD_X] = {{false, "getcwd_x", 0}},
        [PPME_SYSCALL_GETDENTS_E] = {{true, NULL}},
        [PPME_SYSCALL_GETDENTS_X] = {{false, "getdents_x", 0}},
        [PPME_SYSCALL_GETDENTS64_E] = {{true, NULL}},
        [PPME_SYSCALL_GETDENTS64_X] = {{false, "getdents64_x", 0}},
        [PPME_SYSCALL_EPOLLWAIT_E] = {{true, NULL}},
        [PPME_SYSCALL_EPOLLWAIT_X] = {{false, "epoll_wait_x", 0}},
        [PPME_SOCKET_GETPEERNAME_E] = {{true, NULL}},
        [PPME_SOCKET_GETPEERNAME_X] = {{false, "getpeername_x", 0}},
        [PPME_SOCKET_GETSOCKNAME_E] = {{true, NULL}},
        [PPME_SOCKET_GETSOCKNAME_X] = {{false, "getsockname_x", 0}},
        [PPME_SYSCALL_MKDIR_2_E] = {{true, NULL}},
        [PPME_SYSCALL_MKDIR_2_X] = {{false, "mkdir_x", 0}},
        [PPME_SYSCALL_MMAP_E] = {{true, NULL}},
        [PPME_SYSCALL_MMAP_X] = {{false, "mmap_x", 0}},
        [PPME_SYSCALL_MUNMAP_E] = {{true, NULL}},
        [PPME_SYSCALL_MUNMAP_X] = {{false, "munmap_x", 0}},
        [PPME_SYSCALL_OPEN_E] = {{true, NULL}},
        [PPME_SYSCALL_OPEN_X] = {{false, "open_x", 0}},
        [PPME_SYSCALL_OPENAT_2_E] = {{true, NULL}},
        [PPME_SYSCALL_OPENAT_2_X] = {{false, "openat_x", 0}},
        [PPME_SYSCALL_OPENAT2_E] = {{true, NULL}},
        [PPME_SYSCALL_OPENAT2_X] = {{false, "openat2_x", 0}},
        [PPME_SYSCALL_OPEN_BY_HANDLE_AT_E] = {{false, "open_by_handle_at_e", 0}},
        [PPME_SYSCALL_OPEN_BY_HANDLE_AT_X] = {{false, "open_by_handle_at_x", 0}},
        [PPME_SYSCALL_CLOSE_E] = {{false, "close_e", 0}},
        [PPME_SYSCALL_CLOSE_X] = {{false, "close_x", 0}},
        [PPME_SYSCALL_COPY_FILE_RANGE_E] = {{true, NULL}},
        [PPME_SYSCALL_COPY_FILE_RANGE_X] = {{false, "copy_file_range_x", 0}},
        [PPME_SYSCALL_CREAT_E] = {{true, NULL}},
        [PPME_SYSCALL_CREAT_X] = {{false, "creat_x", 0}},
        [PPME_SYSCALL_DUP_1_E] = {{true, NULL}},
        [PPME_SYSCALL_DUP_1_X] = {{false, "dup_x", 0}},
        [PPME_SYSCALL_DUP2_E] = {{true, NULL}},
        [PPME_SYSCALL_DUP2_X] = {{false, "dup2_x", 0}},
        [PPME_SYSCALL_DUP3_E] = {{true, NULL}},
        [PPME_SYSCALL_DUP3_X] = {{false, "dup3_x", 0}},
        [PPME_SYSCALL_CHDIR_E] = {{false, "chdir_e", 0}},
        [PPME_SYSCALL_CHDIR_X] = {{false, "chdir_x", 0}},
        [PPME_SYSCALL_CHMOD_E] = {{false, "chmod_e", 0}},
        [PPME_SYSCALL_CHMOD_X] = {{false, "chmod_x", 0}},
        [PPME_SYSCALL_CHROOT_E] = {{false, "chroot_e", 0}},
        [PPME_SYSCALL_CHROOT_X] = {{false, "chroot_x", 0}},
        [PPME_SYSCALL_FCHDIR_E] = {{true, NULL}},
        [PPME_SYSCALL_FCHDIR_X] = {{false, "fchdir_x", 0}},
        [PPME_SYSCALL_FCHMOD_E] = {{false, "fchmod_e", 0}},
        [PPME_SYSCALL_FCHMOD_X] = {{false, "fchmod_x", 0}},
        [PPME_SYSCALL_FCHMODAT_E] = {{false, "fchmodat_e", 0}},
        [PPME_SYSCALL_FCHMODAT_X] = {{false, "fchmodat_x", 0}},
        [PPME_SYSCALL_MKDIRAT_E] = {{true, NULL}},
        [PPME_SYSCALL_MKDIRAT_X] = {{false, "mkdirat_x", 0}},
        [PPME_SYSCALL_RMDIR_2_E] = {{true, NULL}},
        [PPME_SYSCALL_RMDIR_2_X] = {{false, "rmdir_x", 0}},
        [PPME_SYSCALL_EVENTFD_E] = {{true, NULL}},
        [PPME_SYSCALL_EVENTFD_X] = {{false, "eventfd_x", 0}},
        [PPME_SYSCALL_INOTIFY_INIT_E] = {{true, NULL}},
        [PPME_SYSCALL_INOTIFY_INIT_X] = {{false, "inotify_init_x", 0}},
        [PPME_SYSCALL_TIMERFD_CREATE_E] = {{true, NULL}},
        [PPME_SYSCALL_TIMERFD_CREATE_X] = {{false, "timerfd_create_x", 0}},
        [PPME_SYSCALL_USERFAULTFD_E] = {{false, "userfaultfd_e", 0}},
        [PPME_SYSCALL_USERFAULTFD_X] = {{false, "userfaultfd_x", 0}},
        [PPME_SYSCALL_SIGNALFD_E] = {{false, "signalfd_e", 0}},
        [PPME_SYSCALL_SIGNALFD_X] = {{false, "signalfd_x", 0}},
        [PPME_SYSCALL_KILL_E] = {{true, NULL}},
        [PPME_SYSCALL_KILL_X] = {{false, "kill_x", 0}},
        [PPME_SYSCALL_TGKILL_E] = {{true, NULL}},
        [PPME_SYSCALL_TGKILL_X] = {{false, "tgkill_x", 0}},
        [PPME_SYSCALL_TKILL_E] = {{true, NULL}},
        [PPME_SYSCALL_TKILL_X] = {{false, "tkill_x", 0}},
        [PPME_SYSCALL_SECCOMP_E] = {{false, "seccomp_e", 0}},
        [PPME_SYSCALL_SECCOMP_X] = {{false, "seccomp_x", 0}},
        [PPME_SYSCALL_PTRACE_E] = {{true, NULL}},
        [PPME_SYSCALL_PTRACE_X] = {{false, "ptrace_x", 0}},
        [PPME_SYSCALL_CAPSET_E] = {{true, NULL}},
        [PPME_SYSCALL_CAPSET_X] = {{false, "capset_x", 0}},
        [PPME_SOCKET_SOCKET_E] = {{false, "socket_e", 0}},
        [PPME_SOCKET_SOCKET_X] = {{false, "socket_x", 0}},
        [PPME_SOCKET_CONNECT_E] = {{false, "connect_e_raw_tp", 0}},
        [PPME_SOCKET_CONNECT_X] = {{false, "connect_x", 0}},
        [PPME_SOCKET_SOCKETPAIR_E] = {{true, NULL}},
        [PPME_SOCKET_SOCKETPAIR_X] = {{false, "socketpair_x", 0}},
        [PPME_SOCKET_ACCEPT_5_E] = {{false, "accept_e", 0}},
        [PPME_SOCKET_ACCEPT_5_X] = {{false, "accept_x", 0}},
        [PPME_SOCKET_BIND_E] = {{false, "bind_e", 0}},
        [PPME_SOCKET_BIND_X] = {{false, "bind_x", 0}},
        [PPME_SOCKET_LISTEN_E] = {{false, "listen_e", 0}},
        [PPME_SOCKET_LISTEN_X] = {{false, "listen_x", 0}},
        [PPME_SYSCALL_EXECVE_19_E] = {{false, "execve_e", 0}},
        [PPME_SYSCALL_EXECVE_19_X] = {{false, "execve_x", 0}},
        [PPME_SYSCALL_EXECVEAT_E] = {{false, "execveat_e", 0}},
        [PPME_SYSCALL_EXECVEAT_X] = {{false, "execveat_x", 0}},
        [PPME_SYSCALL_CLONE_20_E] = {{false, "clone_e", 0}},
        [PPME_SYSCALL_CLONE_20_X] = {{false, "clone_x", 0}},
        [PPME_SYSCALL_CLONE3_E] = {{false, "clone3_e", 0}},
        [PPME_SYSCALL_CLONE3_X] = {{false, "clone3_x", 0}},
        [PPME_SYSCALL_FORK_20_E] = {{false, "fork_e", 0}},
        [PPME_SYSCALL_FORK_20_X] = {{false, "fork_x", 0}},
        [PPME_SYSCALL_VFORK_20_E] = {{false, "vfork_e", 0}},
        [PPME_SYSCALL_VFORK_20_X] = {{false, "vfork_x", 0}},
        [PPME_SYSCALL_RENAME_E] = {{true, NULL}},
        [PPME_SYSCALL_RENAME_X] = {{false, "rename_x", 0}},
        [PPME_SYSCALL_RENAMEAT_E] = {{true, NULL}},
        [PPME_SYSCALL_RENAMEAT_X] = {{false, "renameat_x", 0}},
        [PPME_SYSCALL_RENAMEAT2_E] = {{true, NULL}},
        [PPME_SYSCALL_RENAMEAT2_X] = {{false, "renameat2_x", 0}},
        [PPME_SYSCALL_PIPE_E] = {{true, NULL}},
        [PPME_SYSCALL_PIPE_X] = {{false, "pipe_x", 0}},
        [PPME_SYSCALL_READV_E] = {{false, "readv_e", 0}},
        [PPME_SYSCALL_READV_X] = {{false, "readv_x", 0}},
        [PPME_SYSCALL_PREADV_E] = {{false, "preadv_e", 0}},
        [PPME_SYSCALL_PREADV_X] = {{false, "preadv_x", 0}},
        [PPME_SYSCALL_PREAD_E] = {{false, "pread64_e", 0}},
        [PPME_SYSCALL_PREAD_X] = {{false, "pread64_x", 0}},
        [PPME_SYSCALL_BPF_2_E] = {{false, "bpf_e", 0}},
        [PPME_SYSCALL_BPF_2_X] = {{false, "bpf_x", 0}},
        [PPME_SYSCALL_FLOCK_E] = {{true, NULL}},
        [PPME_SYSCALL_FLOCK_X] = {{false, "flock_x", 0}},
        [PPME_SYSCALL_IOCTL_3_E] = {{false, "ioctl_e", 0}},
        [PPME_SYSCALL_IOCTL_3_X] = {{false, "ioctl_x", 0}},
        [PPME_SYSCALL_QUOTACTL_E] = {{false, "quotactl_e", 0}},
        [PPME_SYSCALL_QUOTACTL_X] = {{false, "quotactl_x", 0}},
        [PPME_SYSCALL_UNSHARE_E] = {{false, "unshare_e", 0}},
        [PPME_SYSCALL_UNSHARE_X] = {{false, "unshare_x", 0}},
        [PPME_SYSCALL_MOUNT_E] = {{true, NULL}},
        [PPME_SYSCALL_MOUNT_X] = {{false, "mount_x", 0}},
        [PPME_SYSCALL_UMOUNT2_E] = {{true, NULL}},
        [PPME_SYSCALL_UMOUNT2_X] = {{false, "umount2_x", 0}},
        [PPME_SYSCALL_LINK_2_E] = {{true, NULL}},
        [PPME_SYSCALL_LINK_2_X] = {{false, "link_x", 0}},
        [PPME_SYSCALL_LINKAT_2_E] = {{true, NULL}},
        [PPME_SYSCALL_LINKAT_2_X] = {{false, "linkat_x", 0}},
        [PPME_SYSCALL_SYMLINK_E] = {{true, NULL}},
        [PPME_SYSCALL_SYMLINK_X] = {{false, "symlink_x", 0}},
        [PPME_SYSCALL_SYMLINKAT_E] = {{true, NULL}},
        [PPME_SYSCALL_SYMLINKAT_X] = {{false, "symlinkat_x", 0}},
        [PPME_SYSCALL_UNLINK_2_E] = {{true, NULL}},
        [PPME_SYSCALL_UNLINK_2_X] = {{false, "unlink_x", 0}},
        [PPME_SYSCALL_UNLINKAT_2_E] = {{true, NULL}},
        [PPME_SYSCALL_UNLINKAT_2_X] = {{false, "unlinkat_x", 0}},
        [PPME_SYSCALL_SETGID_E] = {{true, NULL}},
        [PPME_SYSCALL_SETGID_X] = {{false, "setgid_x", 0}},
        [PPME_SYSCALL_SETUID_E] = {{true, NULL}},
        [PPME_SYSCALL_SETUID_X] = {{false, "setuid_x", 0}},
        [PPME_SYSCALL_SETNS_E] = {{true, NULL}},
        [PPME_SYSCALL_SETNS_X] = {{false, "setns_x", 0}},
        [PPME_SYSCALL_SETPGID_E] = {{true, NULL}},
        [PPME_SYSCALL_SETPGID_X] = {{false, "setpgid_x", 0}},
        [PPME_SYSCALL_SETRESGID_E] = {{true, NULL}},
        [PPME_SYSCALL_SETRESGID_X] = {{false, "setresgid_x", 0}},
        [PPME_SYSCALL_SETRESUID_E] = {{true, NULL}},
        [PPME_SYSCALL_SETRESUID_X] = {{false, "setresuid_x", 0}},
        [PPME_SYSCALL_SETSID_E] = {{false, "setsid_e", 0}},
        [PPME_SYSCALL_SETSID_X] = {{false, "setsid_x", 0}},
        [PPME_SYSCALL_SETRLIMIT_E] = {{false, "setrlimit_e", 0}},
        [PPME_SYSCALL_SETRLIMIT_X] = {{false, "setrlimit_x", 0}},
        [PPME_SYSCALL_PRLIMIT_E] = {{true, NULL}},
        [PPME_SYSCALL_PRLIMIT_X] = {{false, "prlimit64_x", 0}},
        [PPME_SOCKET_SETSOCKOPT_E] = {{true, NULL}},
        [PPME_SOCKET_SETSOCKOPT_X] = {{false, "setsockopt_x", 0}},
        [PPME_SOCKET_SENDMSG_E] = {{false, "sendmsg_e", 0}},
        [PPME_SOCKET_SENDMSG_X] = {{false, "sendmsg_x", 0}},
        [PPME_SOCKET_SENDTO_E] = {{false, "sendto_e", 0}},
        [PPME_SOCKET_SENDTO_X] = {{false, "sendto_x", 0}},
        [PPME_SOCKET_RECVMSG_E] = {{false, "recvmsg_e", 0}},
        [PPME_SOCKET_RECVMSG_X] = {{false, "recvmsg_x", 0}},
        [PPME_SOCKET_RECVFROM_E] = {{false, "recvfrom_e", 0}},
        [PPME_SOCKET_RECVFROM_X] = {{false, "recvfrom_x", 0}},
        [PPME_SYSCALL_FCNTL_E] = {{true, NULL}},
        [PPME_SYSCALL_FCNTL_X] = {{false, "fcntl_x", 0}},
        [PPME_SOCKET_SHUTDOWN_E] = {{false, "shutdown_e", 0}},
        [PPME_SOCKET_SHUTDOWN_X] = {{false, "shutdown_x", 0}},
        [PPME_SYSCALL_FSCONFIG_E] = {{false, "fsconfig_e", 0}},
        [PPME_SYSCALL_FSCONFIG_X] = {{false, "fsconfig_x", 0}},
        [PPME_SYSCALL_EPOLL_CREATE_E] = {{true, NULL}},
        [PPME_SYSCALL_EPOLL_CREATE_X] = {{false, "epoll_create_x", 0}},
        [PPME_SYSCALL_EPOLL_CREATE1_E] = {{true, NULL}},
        [PPME_SYSCALL_EPOLL_CREATE1_X] = {{false, "epoll_create1_x", 0}},
        [PPME_SYSCALL_ACCESS_E] = {{true, NULL}},
        [PPME_SYSCALL_ACCESS_X] = {{false, "access_x", 0}},
        [PPME_SOCKET_GETSOCKOPT_E] = {{true, NULL}},
        [PPME_SOCKET_GETSOCKOPT_X] = {{false, "getsockopt_x", 0}},
        [PPME_SYSCALL_MPROTECT_E] = {{true, NULL}},
        [PPME_SYSCALL_MPROTECT_X] = {{false, "mprotect_x", 0}},
        [PPME_SYSCALL_GETUID_E] = {{true, NULL}},
        [PPME_SYSCALL_GETUID_X] = {{false, "getuid_x", 0}},
        [PPME_SYSCALL_GETGID_E] = {{true, NULL}},
        [PPME_SYSCALL_GETGID_X] = {{false, "getgid_x", 0}},
        [PPME_SYSCALL_GETEUID_E] = {{true, NULL}},
        [PPME_SYSCALL_GETEUID_X] = {{false, "geteuid_x", 0}},
        [PPME_SYSCALL_GETEGID_E] = {{true, NULL}},
        [PPME_SYSCALL_GETEGID_X] = {{false, "getegid_x", 0}},
        [PPME_SYSCALL_MLOCK_E] = {{true, NULL}},
        [PPME_SYSCALL_MLOCK_X] = {{false, "mlock_x", 0}},
        [PPME_SYSCALL_MLOCK2_E] = {{true, NULL}},
        [PPME_SYSCALL_MLOCK2_X] = {{false, "mlock2_x", 0}},
        [PPME_SYSCALL_MUNLOCK_E] = {{true, NULL}},
        [PPME_SYSCALL_MUNLOCK_X] = {{false, "munlock_x", 0}},
        [PPME_SYSCALL_MLOCKALL_E] = {{true, NULL}},
        [PPME_SYSCALL_MLOCKALL_X] = {{false, "mlockall_x", 0}},
        [PPME_SYSCALL_MUNLOCKALL_E] = {{true, NULL}},
        [PPME_SYSCALL_MUNLOCKALL_X] = {{false, "munlockall_x", 0}},
        [PPME_SYSCALL_READ_E] = {{false, "read_e", 0}},
        [PPME_SYSCALL_READ_X] = {{false, "read_x", 0}},
        [PPME_SYSCALL_IO_URING_ENTER_E] = {{true, NULL}},
        [PPME_SYSCALL_IO_URING_ENTER_X] = {{false, "io_uring_enter_x", 0}},
        [PPME_SYSCALL_IO_URING_REGISTER_E] = {{true, NULL}},
        [PPME_SYSCALL_IO_URING_REGISTER_X] = {{false, "io_uring_register_x", 0}},
        [PPME_SYSCALL_IO_URING_SETUP_E] = {{true, NULL}},
        [PPME_SYSCALL_IO_URING_SETUP_X] = {{false, "io_uring_setup_x", 0}},
        [PPME_SYSCALL_POLL_E] = {{true, NULL}},
        [PPME_SYSCALL_POLL_X] = {{false, "poll_x", 0}},
        [PPME_SYSCALL_PPOLL_E] = {{true, NULL}},
        [PPME_SYSCALL_PPOLL_X] = {{false, "ppoll_x", 0}},
        [PPME_SYSCALL_MMAP2_E] = {{true, NULL}},
        [PPME_SYSCALL_MMAP2_X] = {{false, "mmap2_x", 0}},
        [PPME_SYSCALL_SEMGET_E] = {{true, NULL}},
        [PPME_SYSCALL_SEMGET_X] = {{false, "semget_x", 0}},
        [PPME_SYSCALL_SEMCTL_E] = {{true, NULL}},
        [PPME_SYSCALL_SEMCTL_X] = {{false, "semctl_x", 0}},
        [PPME_SYSCALL_SELECT_E] = {{true, NULL}},
        [PPME_SYSCALL_SELECT_X] = {{false, "select_x", 0}},
        [PPME_SYSCALL_SPLICE_E] = {{true, NULL}},
        [PPME_SYSCALL_SPLICE_X] = {{false, "splice_x", 0}},
        [PPME_SOCKET_RECVMMSG_E] = {{false, "recvmmsg_e", 0}},
        [PPME_SOCKET_RECVMMSG_X] = {{false, "recvmmsg_x", BPF_FUNC_loop},
                                    {false, "recvmmsg_old_x", 0}},
        [PPME_SOCKET_SENDMMSG_E] = {{false, "sendmmsg_e", 0}},
        [PPME_SOCKET_SENDMMSG_X] = {{false, "sendmmsg_x", BPF_FUNC_loop},
                                    {false, "sendmmsg_old_x", 0}},
        [PPME_SYSCALL_SEMOP_E] = {{true, NULL}},
        [PPME_SYSCALL_SEMOP_X] = {{false, "semop_x", 0}},
        [PPME_SYSCALL_GETRESUID_E] = {{true, NULL}},
        [PPME_SYSCALL_GETRESUID_X] = {{false, "getresuid_x", 0}},
        [PPME_SYSCALL_SENDFILE_E] = {{false, "sendfile_e", 0}},
        [PPME_SYSCALL_SENDFILE_X] = {{false, "sendfile_x", 0}},
        [PPME_SYSCALL_FUTEX_E] = {{true, NULL}},
        [PPME_SYSCALL_FUTEX_X] = {{false, "futex_x", 0}},
        [PPME_SYSCALL_STAT_E] = {{true, NULL}},
        [PPME_SYSCALL_STAT_X] = {{false, "stat_x", 0}},
        [PPME_SYSCALL_LSTAT_E] = {{true, NULL}},
        [PPME_SYSCALL_LSTAT_X] = {{false, "lstat_x", 0}},
        [PPME_SYSCALL_FSTAT_E] = {{true, NULL}},
        [PPME_SYSCALL_FSTAT_X] = {{false, "fstat_x", 0}},
        [PPME_SYSCALL_LSEEK_E] = {{true, NULL}},
        [PPME_SYSCALL_LSEEK_X] = {{false, "lseek_x", 0}},
        [PPME_SYSCALL_LLSEEK_E] = {{true, NULL}},
        [PPME_SYSCALL_LLSEEK_X] = {{false, "llseek_x", 0}},
        [PPME_SYSCALL_WRITE_E] = {{false, "write_e", 0}},
        [PPME_SYSCALL_WRITE_X] = {{false, "write_x", 0}},
        [PPME_SYSCALL_WRITEV_E] = {{false, "writev_e", 0}},
        [PPME_SYSCALL_WRITEV_X] = {{false, "writev_x", 0}},
        [PPME_SYSCALL_PWRITEV_E] = {{false, "pwritev_e", 0}},
        [PPME_SYSCALL_PWRITEV_X] = {{false, "pwritev_x", 0}},
        [PPME_SYSCALL_PWRITE_E] = {{false, "pwrite64_e", 0}},
        [PPME_SYSCALL_PWRITE_X] = {{false, "pwrite64_x", 0}},
        [PPME_SYSCALL_GETRESGID_E] = {{true, NULL}},
        [PPME_SYSCALL_GETRESGID_X] = {{false, "getresgid_x", 0}},
        [PPME_SYSCALL_CHOWN_E] = {{true, NULL}},
        [PPME_SYSCALL_CHOWN_X] = {{false, "chown_x", 0}},
        [PPME_SYSCALL_LCHOWN_E] = {{true, NULL}},
        [PPME_SYSCALL_LCHOWN_X] = {{false, "lchown_x", 0}},
        [PPME_SYSCALL_FCHOWN_E] = {{true, NULL}},
        [PPME_SYSCALL_FCHOWN_X] = {{false, "fchown_x", 0}},
        [PPME_SYSCALL_FCHOWNAT_E] = {{true, NULL}},
        [PPME_SYSCALL_FCHOWNAT_X] = {{false, "fchownat_x", 0}},
        [PPME_SYSCALL_BRK_4_E] = {{true, NULL}},
        [PPME_SYSCALL_BRK_4_X] = {{false, "brk_x", 0}},
        [PPME_SYSCALL_GETRLIMIT_E] = {{false, "getrlimit_e", 0}},
        [PPME_SYSCALL_GETRLIMIT_X] = {{false, "getrlimit_x", 0}},
        [PPME_SOCKET_SEND_E] = {{false, "send_e", 0}},
        [PPME_SOCKET_SEND_X] = {{false, "send_x", 0}},
        [PPME_SOCKET_RECV_E] = {{false, "recv_e", 0}},
        [PPME_SOCKET_RECV_X] = {{false, "recv_x", 0}},
        [PPME_SYSCALL_NANOSLEEP_E] = {{true, NULL}},
        [PPME_SYSCALL_NANOSLEEP_X] = {{false, "nanosleep_x", 0}},
        [PPME_SYSCALL_UMOUNT_1_E] = {{true, NULL}},
        [PPME_SYSCALL_UMOUNT_1_X] = {{false, "umount_x", 0}},
        [PPME_SOCKET_ACCEPT4_6_E] = {{false, "accept4_e", 0}},
        [PPME_SOCKET_ACCEPT4_6_X] = {{false, "accept4_x", 0}},
        [PPME_SYSCALL_PIPE2_E] = {{false, "pipe2_e", 0}},
        [PPME_SYSCALL_PIPE2_X] = {{false, "pipe2_x", 0}},
        [PPME_SYSCALL_INOTIFY_INIT1_E] = {{true, NULL}},
        [PPME_SYSCALL_INOTIFY_INIT1_X] = {{false, "inotify_init1_x", 0}},
        [PPME_SYSCALL_EVENTFD2_E] = {{false, "eventfd2_e", 0}},
        [PPME_SYSCALL_EVENTFD2_X] = {{false, "eventfd2_x", 0}},
        [PPME_SYSCALL_SIGNALFD4_E] = {{false, "signalfd4_e", 0}},
        [PPME_SYSCALL_SIGNALFD4_X] = {{false, "signalfd4_x", 0}},
        [PPME_SYSCALL_PRCTL_E] = {{false, "prctl_e", 0}},
        [PPME_SYSCALL_PRCTL_X] = {{false, "prctl_x", 0}},
        [PPME_SYSCALL_MEMFD_CREATE_E] = {{false, "memfd_create_e", 0}},
        [PPME_SYSCALL_MEMFD_CREATE_X] = {{false, "memfd_create_x", 0}},
        [PPME_SYSCALL_PIDFD_GETFD_E] = {{true, NULL}},
        [PPME_SYSCALL_PIDFD_GETFD_X] = {{false, "pidfd_getfd_x", 0}},
        [PPME_SYSCALL_PIDFD_OPEN_E] = {{true, NULL}},
        [PPME_SYSCALL_PIDFD_OPEN_X] = {{false, "pidfd_open_x", 0}},
        [PPME_SYSCALL_INIT_MODULE_E] = {{true, NULL}},
        [PPME_SYSCALL_INIT_MODULE_X] = {{false, "init_module_x", 0}},
        [PPME_SYSCALL_FINIT_MODULE_E] = {{true, NULL}},
        [PPME_SYSCALL_FINIT_MODULE_X] = {{false, "finit_module_x", 0}},
        [PPME_SYSCALL_MKNOD_E] = {{false, "mknod_e", 0}},
        [PPME_SYSCALL_MKNOD_X] = {{false, "mknod_x", 0}},
        [PPME_SYSCALL_MKNODAT_E] = {{false, "mknodat_e", 0}},
        [PPME_SYSCALL_MKNODAT_X] = {{false, "mknodat_x", 0}},
        [PPME_SYSCALL_NEWFSTATAT_E] = {{false, "newfstatat_e", 0}},
        [PPME_SYSCALL_NEWFSTATAT_X] = {{false, "newfstatat_x", 0}},
        [PPME_SYSCALL_PROCESS_VM_READV_E] = {{false, "process_vm_readv_e", 0}},
        [PPME_SYSCALL_PROCESS_VM_READV_X] = {{false, "process_vm_readv_x", 0}},
        [PPME_SYSCALL_PROCESS_VM_WRITEV_E] = {{false, "process_vm_writev_e", 0}},
        [PPME_SYSCALL_PROCESS_VM_WRITEV_X] = {{false, "process_vm_writev_x", 0}},
        [PPME_SYSCALL_DELETE_MODULE_E] = {{false, "delete_module_e", 0}},
        [PPME_SYSCALL_DELETE_MODULE_X] = {{false, "delete_module_x", 0}},
        [PPME_SYSCALL_SETREUID_E] = {{false, "setreuid_e", 0}},
        [PPME_SYSCALL_SETREUID_X] = {{false, "setreuid_x", 0}},
        [PPME_SYSCALL_SETREGID_E] = {{false, "setregid_e", 0}},
        [PPME_SYSCALL_SETREGID_X] = {{false, "setregid_x", 0}},
        // TODO(ekoops): remove the following entries once the sys_enter dispatcher is dropped.
        // The following entries are added in order to avoid the common generic_e enter event
        // handler to be used as a fallback for the corresponding event types.
        [PPME_SYSCALL_STAT64_E] = {{true, NULL}},
        [PPME_SYSCALL_LSTAT64_E] = {{true, NULL}},
        [PPME_SYSCALL_FSTAT64_E] = {{true, NULL}},
};

ttm_progs_t ttm_progs_table[TTM_MAX] = {
        [TTM_CONNECT] = {{"connect_e"},
                         {{"ia32_compat_connect_e", "__ia32_compat_sys_connect"},
                          {"ia32_connect_e", "__ia32_sys_connect"}}},
        [TTM_CREAT] = {{"creat_e"},
                       {{"ia32_compat_creat_e", "__ia32_compat_sys_creat"},
                        {"ia32_creat_e", "__ia32_sys_creat"}}},
        [TTM_OPEN] = {{"open_e"},
                      {{"ia32_compat_open_e", "__ia32_compat_sys_open"},
                       {"ia32_open_e", "__ia32_sys_open"}}},
        [TTM_OPENAT] = {{"openat_e"},
                        {{"ia32_compat_openat_e", "__ia32_compat_sys_openat"},
                         {"ia32_openat_e", "__ia32_sys_openat"}}},
        [TTM_OPENAT2] = {{"openat2_e"},
                         {{"ia32_compat_openat2_e", "__ia32_compat_sys_openat2"},
                          {"ia32_openat2_e", "__ia32_sys_openat2"}}},
};
