Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox"
  config.ssh.forward_agent = true

  config.vm.define "centos7" do | m |
    m.vm.box = "bento/centos-7"
    m.vm.hostname = "centos7"
    m.vbguest.auto_update = false
    m.vm.synced_folder '.', '/vagrant', disabled: true
    m.vm.network "private_network", ip: ENV["LIBS_CENTOS7_IP"] || "192.168.56.25"
  end

  config.vm.define "ubuntu" do | m |
    m.vm.box = "bento/ubuntu-20.04"
    m.vm.hostname = "ubuntu"
    m.vbguest.auto_update = false
    m.vm.synced_folder '.', '/vagrant', disabled: true
    m.vm.network "private_network", ip: ENV["LIBS_UBUNTU2004_IP"] || "192.168.56.26"
  end

end
