Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox"
  config.ssh.forward_agent = true

  config.vm.define "centos7" do | m |
    m.vm.box = "bento/centos-7"
    m.vm.hostname = "centos7"
    m.vbguest.auto_update = false
    m.vm.network "private_network", ip: "192.168.56.25"
  end

  config.vm.define "ubuntu" do | m |
    m.vm.box = "bento/ubuntu-20.04"
    m.vm.hostname = "ubuntu"
    m.vbguest.auto_update = false
    m.vm.network "private_network", ip: "192.168.56.26"
  end

end
