#!/usr/bin/env bash
#
# Rebuild the starting seed corpus for fuzz_scap_event_decode.
#
# "Seed corpus" here means the small set of inputs libFuzzer starts from
# before it begins mutating them.
#
# The corpus has two parts:
#   1. Real events extracted from in-repo .scap capture files.
#   2. Synthetic events built by hand to hit specific decoder paths
#      (large-payload types, schema-clamp, zero-length params, etc.).
#
# The output is a flat directory of .bin files, one per seed. The default
# output lives under /tmp because these are generated artifacts, not source
# files that need to be committed.
#
# Run this whenever the harness or event table changes.
#
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
TOOLS_DIR="$ROOT_DIR/test/libscap/fuzz/tools"

WORK_DIR="${WORK_DIR:-/tmp/falco-libs-corpus-rebuild}"
BUILD_DIR="$WORK_DIR/build"
EXTRACTOR_BIN="$BUILD_DIR/test/libscap/fuzz/tools/extract_scap_events"
EXTRACTED_DIR="$WORK_DIR/extracted"
DEFAULT_CORPUS_DIR="$WORK_DIR/corpus/fuzz_scap_event_decode"
CORPUS_DIR="${CORPUS_DIR:-$DEFAULT_CORPUS_DIR}"
# Marker used to tell whether a custom CORPUS_DIR was previously created by
# this script, so we can replace it safely on later runs.
CORPUS_MARKER_PATH="${CORPUS_DIR}.generated-by-recreate_seed_corpus"
STAGING_CORPUS_DIR=""
MAX_EVENTS="${MAX_EVENTS:-500}"
MAX_LEN="${MAX_LEN:-4096}"
NPROC="$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)"

cleanup() {
  if [[ -n "${STAGING_CORPUS_DIR:-}" && -d "$STAGING_CORPUS_DIR" ]]; then
    rm -rf "$STAGING_CORPUS_DIR"
  fi
}
trap cleanup EXIT

echo "[1/7] Preparing workspace: $WORK_DIR"
mkdir -p "$WORK_DIR"
STAGING_CORPUS_DIR="$(mktemp -d "$WORK_DIR/corpus-staging.XXXXXX")"

# Configure a static libscap build plus the helper that reads in-repo sample
# captures without depending on an installed shared library.
echo "[2/7] Configuring extractor helper build"
cmake -S "$ROOT_DIR" -B "$BUILD_DIR" \
  -DCMAKE_BUILD_TYPE=Release \
  -DUSE_BUNDLED_DEPS=ON \
  -DBUILD_SHARED_LIBS=OFF \
  -DHAVE_LIBSINSP=OFF \
  -DCREATE_TEST_TARGETS=OFF \
  -DENABLE_LIBSCAP_FUZZ_TOOLS=ON \
  -DBUILD_LIBSCAP_EXAMPLES=OFF

echo "[3/7] Building extractor helper"
cmake --build "$BUILD_DIR" --target extract_scap_events -j"$NPROC"

# Pull individual events out of the sample captures checked into the repo.
echo "[4/7] Extracting raw events from in-repo sample captures"
mkdir -p "$EXTRACTED_DIR/curl_google" "$EXTRACTED_DIR/test_ipv6_client"

"$EXTRACTOR_BIN" \
  "$ROOT_DIR/test/libsinsp_e2e/resources/captures/curl_google.scap" \
  "$EXTRACTED_DIR/curl_google" \
  "$MAX_EVENTS" \
  "$MAX_LEN"

"$EXTRACTOR_BIN" \
  "$ROOT_DIR/test/libsinsp_e2e/resources/captures/test_ipv6_client.scap" \
  "$EXTRACTED_DIR/test_ipv6_client" \
  "$MAX_EVENTS" \
  "$MAX_LEN"

# Assemble the final corpus from:
#   1. a hand-picked subset of real events from sample captures
#   2. synthetic events that target decoder branches the real captures do not
#      reliably reach on their own
echo "[5/7] Recreating deterministic seed subset"
python3 "$TOOLS_DIR/recreate_seed_corpus.py" "$ROOT_DIR" "$STAGING_CORPUS_DIR" "$EXTRACTED_DIR"

echo "[6/7] Installing corpus into $CORPUS_DIR"
if [[ "$CORPUS_DIR" == "$DEFAULT_CORPUS_DIR" ]]; then
  # For the default path, we fully own the directory and always replace it.
  rm -rf "$CORPUS_DIR"
else
  # For a custom path, only replace an empty directory or one previously
  # created by this script. That avoids deleting unrelated user files.
  if [[ -d "$CORPUS_DIR" ]] && [[ ! -f "$CORPUS_MARKER_PATH" ]] \
    && find "$CORPUS_DIR" -mindepth 1 -maxdepth 1 -print -quit | grep -q .; then
    echo "refusing to replace non-empty CORPUS_DIR without marker: $CORPUS_DIR"
    echo "use an empty dedicated directory, or remove it first"
    exit 1
  fi
  rm -rf "$CORPUS_DIR"
fi

mkdir -p "$(dirname "$CORPUS_DIR")"
rm -f "$CORPUS_MARKER_PATH"
mv "$STAGING_CORPUS_DIR" "$CORPUS_DIR"
printf 'generated by recreate_seed_corpus.sh\n' > "$CORPUS_MARKER_PATH"
STAGING_CORPUS_DIR=""

# Quick sanity check: list files and total size for the rebuilt baseline.
echo "[7/7] Corpus summary"
find "$CORPUS_DIR" -maxdepth 1 -type f -name '*.bin' -print | sort
echo "total files: $(find "$CORPUS_DIR" -maxdepth 1 -type f -name '*.bin' | wc -l | tr -d ' ')"
echo "total bytes: $(find "$CORPUS_DIR" -maxdepth 1 -type f -name '*.bin' -print0 | xargs -0 wc -c | tail -n1 | awk '{print $1}')"
