FROM docker.io/library/ubuntu:20.04
# https://ubuntu.com/about/release-cycle, LTS until 2030

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y
RUN apt --fix-broken -y install
RUN apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl libncurses5-dev libncursesw5-dev \
xz-utils tk-dev libffi-dev liblzma-dev jq golang build-essential git libncurses-dev pkg-config autoconf libtool libelf-dev \
libssl-dev libc-ares-dev libprotobuf-dev protobuf-compiler libjq-dev libgrpc++-dev protobuf-compiler-grpc libcurl4-openssl-dev libyaml-cpp-dev cmake rpm libelf-dev
RUN apt-get install -y rpm2cpio cpio sudo zstd
RUN apt-get install -y llvm-7 clang-7 gcc-7
RUN apt-get install -y llvm-8 clang-8 gcc-8
RUN apt-get install -y llvm-9 clang-9 gcc-9
RUN apt-get install -y llvm-10 clang-10 gcc-10
RUN ln -s -T /usr/bin/make /usr/bin/gmake
RUN apt install libc6 -y

ENTRYPOINT ["/bin/bash", "-c"]
