FROM ubuntu:23.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update -y
RUN apt --fix-broken -y install
RUN apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl libncurses5-dev libncursesw5-dev \
xz-utils tk-dev libffi-dev liblzma-dev jq golang build-essential git libncurses-dev pkg-config autoconf libtool libelf-dev \
libssl-dev libc-ares-dev libprotobuf-dev protobuf-compiler libjq-dev libgrpc++-dev protobuf-compiler-grpc libcurl4-openssl-dev libyaml-cpp-dev cmake rpm libelf-dev
RUN apt-get install -y rpm2cpio cpio sudo zstd
RUN apt-get install -y llvm-13 clang-13 gcc-13
RUN apt-get install -y llvm-14 clang-14
RUN apt-get install -y llvm-15 clang-15
RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-15 90
RUN update-alternatives --install /usr/bin/llvm-strip llvm-strip /usr/bin/llvm-strip-15 90
RUN apt install libc6 -y
RUN git clone https://github.com/libbpf/bpftool.git --branch v7.0.0 --single-branch && cd bpftool && git submodule update --init && cd src && make && make install

ENTRYPOINT ["/bin/bash", "-c"]
