FROM docker.io/library/ubuntu:22.04
# https://ubuntu.com/about/release-cycle, LTS until 2032

ARG DEBIAN_FRONTEND=noninteractive

# need Docker >= 20.10.9 to not run into known issue `Problem executing scripts DPkg::Post-Invoke 'rm -f /var/cache/apt/archives/*.deb /var/cache/apt/archives/partial/*.deb /var/cache/apt/*.bin || true'`
RUN apt-get update -y
RUN apt --fix-broken -y install
RUN apt-get install -y build-essential libssl-dev zlib1g-dev libbz2-dev \
libreadline-dev libsqlite3-dev wget curl libncurses5-dev libncursesw5-dev \
xz-utils tk-dev libffi-dev liblzma-dev jq golang build-essential git libncurses-dev pkg-config autoconf libtool libelf-dev \
libssl-dev libc-ares-dev libprotobuf-dev protobuf-compiler libjq-dev libgrpc++-dev protobuf-compiler-grpc libcurl4-openssl-dev libyaml-cpp-dev cmake rpm libelf-dev
RUN apt-get install -y rpm2cpio cpio sudo zstd
RUN apt-get install -y gcc-9 gcc-10
RUN apt-get install -y llvm-11 clang-11 gcc-11
RUN apt-get install -y llvm-12 clang-12 gcc-12
RUN apt-get install -y llvm-13 clang-13
RUN apt-get install -y llvm-14 clang-14
RUN apt install libc6 -y
RUN apt install python3 python3-pip -y
RUN pip install pandas==1.4.3 requests==2.28.1 matplotlib==3.5.2 seaborn==0.11.1


ENTRYPOINT ["/bin/bash", "-c"]
