#
# $Id: Makefile 4029 2024-01-15 16:16:49Z jkoshy $
#

TOP=		../../../..

SUBDIR+=	dwarf_init
SUBDIR+=	dwarf_next_cu_header
SUBDIR+=	dwarf_get_address_size
SUBDIR+=	dwarf_siblingof
SUBDIR+=	dwarf_child
SUBDIR+=	dwarf_die_query
SUBDIR+=	dwarf_die_offset
SUBDIR+=	dwarf_die_convenience
SUBDIR+=	dwarf_attr
SUBDIR+=	dwarf_attrlist
SUBDIR+=	dwarf_form
SUBDIR+=	dwarf_loclist
SUBDIR+=	dwarf_lineno
SUBDIR+=	dwarf_frame
SUBDIR+=	dwarf_arange
SUBDIR+=	dwarf_abbrev
SUBDIR+=	dwarf_pubnames
SUBDIR+=	dwarf_macinfo
SUBDIR+=	dwarf_ranges

.include "${TOP}/mk/elftoolchain.subdir.mk"
