name: 'install-zig'
description: 'Install zig compiler and set ZIG/ZIG_TARGET env vars for use with cmake/toolchains/zig.cmake.'

inputs:
  target:
    description: 'Zig target triple (default: <host-arch>-linux-gnu.2.17)'
    required: false
    default: ''
  zig_download_retries:
    description: 'Number of retries for the download'
    required: false
    default: 20

runs:
  using: "composite"
  steps:
    - name: Store zig version as local output
      shell: bash
      id: store
      env:
        ZIG_VERSION: '0.15.1'
      run: |
        echo "zig_version=${ZIG_VERSION}" >> "$GITHUB_OUTPUT"

    - name: Download zig
      shell: bash
      run: |
        wget --tries=${{ inputs.zig_download_retries }} -O zig.tar.xz https://ziglang.org/download/${{ steps.store.outputs.zig_version }}/zig-$(uname -m)-linux-${{ steps.store.outputs.zig_version }}.tar.xz
        tar -xvf zig.tar.xz
        mv zig-$(uname -m)-linux-${{ steps.store.outputs.zig_version }}/ zig

    - name: Setup zig
      shell: bash
      id: zig
      run: |
        ZIG_DIR="$(pwd)/zig"
        echo "${ZIG_DIR}" >> $GITHUB_PATH
        echo "ZIG=${ZIG_DIR}/zig" >> $GITHUB_ENV
        if [ -n "${{ inputs.target }}" ]; then
          echo "ZIG_TARGET=${{ inputs.target }}" >> $GITHUB_ENV
        else
          echo "ZIG_TARGET=$(uname -m)-linux-gnu.2.17" >> $GITHUB_ENV
        fi
        TOOLCHAIN="$(realpath "${{ github.action_path }}/../../../cmake/toolchains/zig.cmake")"
        echo "ZIG_TOOLCHAIN_FILE=${TOOLCHAIN}" >> $GITHUB_ENV
