# $Id: Makefile 4029 2024-01-15 16:16:49Z jkoshy $

TOP=		../../../..

SUBDIR+=	nm_archive1
SUBDIR+=	nm_archive2
SUBDIR+=	nm_debug
SUBDIR+=	nm_object1
SUBDIR+=	nm_object2
SUBDIR+=	nm_option
SUBDIR+=	nm_shared_object1
SUBDIR+=	nm_shared_object2

.include "${TOP}/mk/elftoolchain.subdir.mk"
