name: Builder update
on:
  push:
    branches: [master]
    paths: ['docker/**']

jobs:
  update-builder:
    env:
      REGISTRY: ghcr.io
      BUILDER_IMAGE_BASE: ghcr.io/fededp/libs-builder

    runs-on: ubuntu-latest
    steps:
      - name: Checkout Libs
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build new builder
        id: libs-builder
        uses: docker/build-push-action@v3
        with:
          context: docker
          file: docker/builder.Dockerfile
          platforms: amd64,arm64
          push: true
          tags: ${{ format('{0}:dev,{0}:{1}', env.BUILDER_IMAGE_BASE, github.sha) }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
