# NOTE: it is UNSAFE to run ANY kind of script when using the pull_request_target trigger!
# DO NOT TOUCH THIS FILE UNLESS THE TRIGGER IS CHANGED.
# See warning in https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target.

name: Driver SCHEMA_VERSION checks
on:
  pull_request_target:
    paths:
      - 'driver/ppm_fillers.c'
      - 'driver/bpf/fillers.h'
      - 'driver/event_table.c'
      - 'driver/ppm_events_public.h'
      - 'driver/event_stats.h'
      - 'driver/syscall_*'

jobs:
  paths-filter:
    runs-on: ubuntu-24.04
    outputs:
      driver_schema_changed: ${{ steps.filter.outputs.driver_schema }}
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
      id: filter
      with:
        filters: |
          driver_schema:
            - 'driver/SCHEMA_VERSION'

  driver-schema:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    needs: paths-filter
    if: needs.paths-filter.outputs.driver_schema_changed == 'false'
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Check driver SCHEMA_VERSION
        uses: mshick/add-pr-comment@b8f338c590a895d50bcbfa6c5859251edc8952fc # v2.8.2
        with:
          message: |
            Please double check **driver/SCHEMA_VERSION** file. See [versioning](https://github.com/falcosecurity/libs/blob/master/driver/README.VERSION.md#schema-version-number).

            /hold

      - name: Trigger failure
        run: |
          echo Driver schema version likely needs to be bumped
          cat ./driver/SCHEMA_VERSION
          echo
          echo Please double check **driver/SCHEMA_VERSION** file.
          echo See: https://github.com/falcosecurity/libs/blob/master/driver/README.VERSION.md#schema-version-number.
          exit 1
