name: Test Coverage CI
on:
  pull_request:
  push:
    branches:
      - master

# Checks if any concurrent jobs under the same pull request or branch are being executed
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  unit-test-libsinsp-coverage:
    name: unit-test-libsinsp-coverage 🧐
    runs-on: 'ubuntu-24.04'
    steps:
      - name: Checkout Libs ⤵️
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Install deps ⛓️
        run: |
          sudo apt-get update && sudo apt install -y --no-install-recommends ca-certificates build-essential git clang llvm pkg-config autoconf automake libtool libelf-dev wget libre2-dev libtbb-dev libjq-dev libjsoncpp-dev libgtest-dev linux-headers-$(uname -r) gpg gpg-agent gcovr
          sudo .github/install-deps.sh

      - name: Install cmake 🌊
        uses: ./.github/actions/install-cmake

      - name: Build and test 🏗️🧪
        run: |
          cmake -B build -S . -DBUILD_WARNINGS_AS_ERRORS=True -DENABLE_COVERAGE=True -DUSE_BUNDLED_DEPS=False -DENABLE_THREAD_POOL=ON -DENABLE_MULTI_THREAD=ON
          KERNELDIR=/lib/modules/$(ls /lib/modules)/build cmake --build build --parallel $(nproc)
          cmake --build build --target run-unit-tests --parallel $(nproc)

      - name: Generate libsinsp coverage report
        run: |
          gcovr --gcov-ignore-parse-errors=all --xml -o ./libsinsp.coverage.xml

      - name: Upload to codecov
        uses: codecov/codecov-action@57e3a136b779b570ffcdbf80b3bdc90e7fab3de2 # v6.0.0
        with:
          fail_ci_if_error: true
          files: ./libsinsp.coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          flags: libsinsp
